name: Update repo

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    if: github.repository_owner == 'flathub'

    steps:
      - uses: actions/checkout@v6
      - name: clean old files
        run: rm *.yaml
      - name: get upstream files
        run: |
          wget ${{ github.event.client_payload.url }} -O files.zip
          file files.zip
          unzip -o files.zip
      - name: Create pull request
        if: ${{ success() }}
        id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          branch-suffix: random
          commit-message: Update to latest syng release
          delete-branch: true
          sign-commits: true
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
